// For QuizWipContext
export const FILL_IN_NEW_QUIZ = "FILL_IN_NEW_QUIZ";
export const CATCH_FILL_IN_NEW_QUIZ_FINISH = "CATCH_FILL_IN_NEW_QUIZ_FINISH";
export const CATCH_FILL_IN_NEW_QUIZ_FINISH_FALSE = "CATCH_FILL_IN_NEW_QUIZ_FINISH_FALSE";

export const FILL_IN_QUIZ_EDIT = "FILL_IN_QUIZ_EDIT";
export const SET_LOADING = "SET_LOADING";
export const CURRENT_QUESTION_EDIT = "CURRENT_QUESTION_EDIT";
export const CLEAR_CURRENT_QUESTION_EDIT = "CLEAR_CURRENT_QUESTION_EDIT";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_LOGGED_OFF = "SET_LOGGED_OFF";
export const RENAME_QUIZ = "RENAME_QUIZ";

export const DELETE_QUIZ_WIP = "DELETE_QUIZ_WIP";
export const ADD_QUIZ = "ADD_QUIZ";
export const UPDATE_PRIVATE_QUIZ = "UPDATE_PRIVATE_QUIZ";

export const QUIZWIP_ERROR = "QUIZWIP_ERROR";
export const CLEAR_QUIZ_EDIT = "CLEAR_QUIZ_EDIT";

export const GET_QUIZ_WIPS = "GET_QUIZ_WIPS";
export const CLEAR_QUIZ_WIPS = "CLEAR_QUIZ_WIPS";

export const ALL_QUIZ_NAMES = "ALL_QUIZ_NAMES";
// For QuizPublicContext
export const FILL_IN_QUIZ_EDIT_PUBLIC = "FILL_IN_QUIZ_EDIT_PUBLIC";
export const SET_LOADING_PUBLIC = "SET_LOADING_PUBLIC";
export const CURRENT_PUBLIC_Q_EDIT = "CURRENT_PUBLIC_Q_EDIT";
export const CLEAR_CURRENT_PUBLIC_Q_EDIT = "CLEAR_CURRENT_PUBLIC_Q_EDIT";
export const ADD_QUESTION_PUBLIC = "ADD_QUESTION_PUBLIC";
export const DELETE_QUESTION_PUBLIC = "DELETE_QUESTION_PUBLIC";
export const UPDATE_QUESTION_PUBLIC = "UPDATE_QUESTION_PUBLIC";

export const DELETE_QUIZ_PUBLIC = "DELETE_QUIZ_PUBLIC";
export const ADD_PUBLIC_QUIZ = "ADD_PUBLIC_QUIZ";
export const UPDATE_PUBLIC_QUIZ = "UPDATE_PUBLIC_QUIZ";

export const  SET_TOP_QUIZ = "SET_TOP_QUIZ";

export const FILTER_PUBLIC_QUIZES = "FILTER_PUBLIC_QUIZES";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const QUIZPUB_ERROR = "QUIZPUB_ERROR";

export const GET_QUIZ_PUB = "GET_QUIZ_PUB";
export const CLEAR_QUIZ_PUB = "CLEAR_QUIZ_PUB";

// For PUBLIC ACCESS 
export const ADD_TO_PUBLIC = "ADD_TO_PUBLIC";
export const GET_FROM_PUBLIC = "GET_FROM_PUBLIC";
export const DELETE_FROM_PUBLIC = "DELETE_FROM_PUBLIC";
export const UPDATE_PUBLIC = "UPDATE_PUBLIC";
export const SET_LOADING_PUBLIC_ACCESS = "SET_LOADING_PUBLIC_ACCESS";
export const GET_FROM_PUBLIC_TO_CALC = "GET_FROM_PUBLIC_TO_CALC";
export const FILTER_QUIZ_OWNER_BY_NAME = "FILTER_QUIZ_OWNER_BY_NAME";

// For AllPublicQuizesContext
export const FILTER_ALL_PUBLIC_QUIZES = "FILTER_ALL_PUBLIC_QUIZES";
export const CLEAR_FILTER_ALL_PUBLIC_QUIZES = "CLEAR_FILTER_ALL_PUBLIC_QUIZES";
export const FILL_IN_CURRENT_ACTIVE_QUIZ = "FILL_IN_CURRENT_ACTIVE_QUIZ";

// For Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// For alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";